// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionCallOutputBody } from "../FunctionCallOutputBody";

export type TurnToolOutput = { name: string, namespace: string | null, output: FunctionCallOutputBody, };
